acm-ucr/membership-portal

pages/index.js
=> Changed Index to Testing

components/Announcement.jsx, pages/index.js
appearance on different screen sizes:
=> add announcement card component

components/Home.jsx
=> Rayyan zaid/home component

components/Toggle.jsx, pages/index.js
Included button to change state variable (representing auth status). Can remove this button later.
=> Implemented General and Admin badges to be displayed based on auth status

components/AvailableForms.jsx, components/AvailableFormsArray.jsx, components/CompletedForms.jsx, components/CompletedFormsArray.jsx, components/FormArray.jsx, components/SubmittedForms.jsx, components/SubmittedFormsArray.jsx
kind of just taking a stab at the issue cause i'm still not exactly sure what I'm trying to integrate lmao
Is it supposed to be something like this where Available, Submitted, Completed forms will each have mappings within their own components? Or am I thinking in a different direction
=> add forms array mapping

.gitignore, .prettierignore, components/Home.jsx, components/Navigation.jsx, pages/dashboard.js, pages/forms.js, pages/profile.js, pages/resources.js
=> Fix Nav Overlap

pages/profile.js
=> Add Profile Header

components/SubmittedForm.jsx, components/SubmittedForms.jsx
=> added submitted form

components/AvailableForm.jsx, components/AvailableForms.jsx, components/CompletedForm.jsx, components/CompletedForms.jsx, components/SubmittedForm.jsx, components/SubmittedForms.jsx
=> added compeleted form and edit all the forms

components/Announcements.jsx
=> added announcements title and background

components/Announcements.jsx, pages/forms.js
=> added space between the headers

components/Navigation.jsx
Added "membership portal" text next to the logo.
Here's the issue https://github.com/acm-ucr/membership-portal/issues/55
=> Added membership portal text

components/AvailableForms.jsx, components/AvailableFormsArray.jsx, components/CompletedForms.jsx, components/CompletedFormsArray.jsx, components/SubmittedForms.jsx, components/SubmittedFormsArray.jsx
=> fix data array

components/Welcome.jsx
=> change font for welcome page

components/Navigation.jsx
=> added logout button

components/TimeFilter.jsx
=> fixed time filter border

components/ResumeReviewForm.jsx, pages/forms.js
I added the resume input and comments section as I didn't have it before but the specs wanted it
if yall want to get rid of this form when working on the code go to "pages/forms.js" and umcomment/comment all the ResumeReviewForm stuff.
=> Arnav-Menon/quick fix for #100 to match specs

components/AvailableForm.jsx, components/CompletedForm.jsx, components/MockInterviewForm.jsx, components/MockInterviewFormDetails.jsx, components/Profile.jsx, components/ResumeReviewForm.jsx, components/ResumeReviewFormDetails.jsx, pages/forms.js
=> component pop up

components/Confirmation.jsx, components/Register.jsx
I have not worked with useState before but I think I got the gist of what's happening in the code. Let me know if there are issues.
=> Data Collection

components/Profile.jsx
Screenshots show before attempting to save and after attempting to save
=> Vm sandoval25/year validation

components/Register.jsx
sends alert messages if data input was invalid. let me know if I should check for any other mistakes in the input
seems like there is already this form of validation for empty fields
valid phone number formats included were (123) 456-7890 / (123)456-7890 / 123-456-7890 / 1234567890
=> Add data validation for Register component

components/Resources.jsx
=> no resources messae

components/Profile.jsx
=> fix profile width

package-lock.json, pages/api/profile/getInfo.js
is this what I suppose to do? I am a little confused.
=> Change to use email from auth

pages/user/dashboard.js, pages/user/forms.js, pages/user/profile.js, pages/user/resources.js
added titles to dashboard, forms, profile, resources
=> Issue #190: added titles

components/Navigation.jsx, package-lock.json
=> resized navbar

components/Announcements.jsx, components/Meeting.jsx, components/Meetings.jsx
updated padding & font size for headers
=> Issue 191: Same Size Headers 

components/Home.jsx, components/Meeting.jsx, components/Meetings.jsx, pages/user/dashboard.js
* made dashboard responsive
* adjusted components inside dashboard as well as the dashboard page
=> Dashboard responsiveness

components/Profile.jsx
=> changed breakpoints for input

components/Navigation.jsx
=> Commented out 'forms' tab from navbar

pages/api/get5Announcements.js
* added a query that will only get the 5 most recent queries according to time
* limited query to only 5
* this will prevent having to sort in our code
=> get 5 annoucements query

components/Navigation.jsx, pages/user/calendar.js
* added calendar page to users
* added the page to nav bar
=> calendar navigation

components/Announcements.jsx, components/AvailableForms.jsx, components/Header.jsx, package-lock.json, pages/user/profile.js, pages/user/resources.js
Add the background color for the resource header
=> Add the background of resource header

components/PageError.jsx, pages/user/error400.js, pages/user/error500.js
* added error 400 and 500 pages to user routes
* created a page error comp to use for rendering
* added styles to page error comp to match screen shot
=> Error 400 and 500 pages + PageError comp

components/Announcements.jsx, components/Meetings.jsx
made "scheduled meetings" and "announcements" headers same size.
=> issue 201 making headers same size

components/Profile.jsx
=> dropdown for major

components/Announcement.jsx
=> changed border size

components/Resources.jsx
=> centered no resources text on mobile

components/Navigation.jsx, components/Profile.jsx
=> Centered on Mobile

components/Navigation.jsx
=> made logo and hamburger smaller on mobile

components/Profile.jsx, pages/dashboard.js
=> update sizing in edit profile + tailwind engineering for dashboard

pages/dashboard.js
- zoomed out to get multiple events to show they are the most **recent** events 
- slice(0,5) --> to get the 5 most recent events from google calendar api call
=> fixed slice of events from calendar api call

components/Announcements.jsx, components/Calendar.jsx, components/CardAccess.jsx, components/Home.jsx, components/Login.jsx, components/Navigation.jsx, components/Profile.jsx, components/Resources.jsx, components/TimeFilter.jsx, components/forms/AvailableForm.jsx, components/forms/CompletedForm.jsx, pages/apply.js, pages/clubroom.js, pages/dashboard.js, pages/profile.js
Missed some of the imports that were on the same line w importing useState and such
=> Delete react imports joined with other imports

components/Home.jsx
=> Aligned welcome message

components/ApplicationProfile.jsx, components/ResourceContext.jsx, components/Resources.jsx, pages/_app.js
Used User Context as a reference
Let me know about any errors
=> Implement Resource Context

components/ApplicationProfile.jsx
I'm not sure if I account for all cases of the issue, but the issue stopped happening on my end
=> Ensure image renders once image prop is loaded

components/ApplicationProfile.jsx, pages/invalidRequest.js
I made a separate invalid page, but I realize there might be a more streamlined way to implement the different message into the same invalid page? If so let me know
=> Redirect to prevent verified members from accessing apply page

components/Clubroom.jsx, components/Frame.jsx, pages/clubroom.js
=> Add Clubroom Info

components/Clubroom.jsx, components/Frame.jsx
=> Added Clubroom Fixes

components/CardAccess.jsx
=> Reduced the Spacing

components/Profile.jsx
=> Changed Focus Outline to Black

components/Calendar.jsx, components/CardAccess.jsx, components/CustomEvent.jsx, components/Login.jsx, components/Profile.jsx, components/Resources.jsx, pages/api/getAllResources.js, pages/apply.js, pages/dashboard.js
I left the console.logs that outputted error or something similar.
=> Removed All Console Logs

pages/dashboard.js
=> Add filter colors to academic events

components/Calendar.jsx, pages/calendar.js
=> Fix calendar scrolling

components/ResumeFeedback.jsx, components/ResumeUpload.jsx, pages/clubroom.js, pages/resume.js
=> Resume page

components/CardAccess.jsx, pages/_app.js
=> updated events filtering to keep events from the past

components/Navigation.jsx
=> Resume added to Navigation Bar

components/Clubroom.jsx, pages/clubroom.js
=> Clubroom Header Updated

pages/dashboard.js
=> Spacing reduced in dashboard between welcome header and nav bar

components/CardAccess.jsx
=> Card Access borders more square now

components/ResumeFeedback.jsx, components/ResumeUpload.jsx, pages/resume.js
submit for review still doesn't do anything
=> Change up resume page

components/Resources.jsx, components/TimeFilter.jsx
=> Added Last 6 months option in Resources

components/Clubroom.jsx, pages/clubroom.js
=> Clubroom Page fits within 100vh

components/PDFViewer.jsx
=> Remove PDF Toolbar

components/PDFViewer.jsx, components/ResumeUpload.jsx, pages/api/submitResume.js, pages/resume.js
=> Implement simple resume link validation 

pages/apply.js
=> Redesign apply page

pages/dashboard.js
=> Add no upcoming message to announcements

components/PDFViewer.jsx, components/Resources.jsx, components/TimeFilter.jsx
=> Add default no resume message

pages/invalid.js
=> Vertically Centered Error Message

pages/_app.js
=> Dashboard Shows Month and Year

components/Navigation.jsx
=> Increased Logout Button Padding

pages/clubroom.js
=> Clubroom Spacing Reduced

components/Clubroom.jsx
=> Removed Background in Clubroom

components/CustomToolbar.jsx
=> Made calendar footprint smaller

components/Clubroom.jsx, components/Frame.jsx
Added height and width parameter to Frame/Image component.
=> Give clubroom image more width

components/ResumeUpload.jsx
Deleted array of rules and rules section.  Added spacing between "upload button" and "submit for review button"
=> Removed Rules Section of Resume Upload

components/Clubroom.jsx
"/clubroom.webp" instead of "./clubroom.webp"
=> Change clubroom image source to correct file

components/Navigation.jsx
no way i just made 3 commits for that
=> logo directs to /user/dashboard

components/Announcements.jsx, pages/user/dashboard.js
I've been working on issue #461 in aligning the announcements to the top of the container but when I used "align-top" nothing seemed to change. Tried to debug by putting align-top in different places but nothing seemed to change. I'm not too sure if this is the correct approach.
=> Issue using top-align

components/PDFViewer.jsx, pages/user/resume.js
=> Centers the Resume Preview When Resume is Found
